name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        java-version: ["8", "11", "17"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v2"

    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: ${{ matrix.java-version }}

    - name: "Restore Cache"
      uses: "actions/cache@v1"
      with:
        path: "~/.m2/repository"
        key: "${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}"
        restore-keys: "${{ runner.os }}-deps-"

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@10.3
      with:
        cli: 1.10.3.1040

    - name: Download deps
      run: |
        clojure -P -M:clj-1.9
        clojure -P -M:clj-1.10
        clojure -P -M:clj-1.11

    - name: Run tests not Windows
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        clojure -M:clj-1.9:test -e windows
        clojure -M:clj-1.10:test -e windows
        clojure -M:clj-1.11:test -e windows
      shell: bash

    - name: Run tests on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        clojure -M:clj-1.9:test -i windows
        clojure -M:clj-1.10:test -i windows
        clojure -M:clj-1.11:test -i windows
      shell: powershell
