name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java-version: ["8", "11", "17"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v3"

    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java-version }}

    - name: "Restore Cache"
      uses: "actions/cache@v3"
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: "${{ runner.os }}-deps-${{ hashFiles('deps.edn','bb.edn') }}"

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@10.3
      with:
        cli: 1.10.3.1040
        bb: 'latest'

    - name: Download bb deps
      run:
        bb --version

    - name: Run tests
      run: |
        clojure -M:clj-1.9:test
        clojure -M:clj-1.10:test
        clojure -M:clj-1.11:test
