name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        java-version: ["8", "11", "17"]
        clojure-version: ["1.9","1.10", "1.11"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v2"

    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: ${{ matrix.java-version }}

    - name: "Restore Cache"
      uses: "actions/cache@v1"
      with:
        path: "~/.m2/repository"
        key: "${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}"
        restore-keys: "${{ runner.os }}-deps-"

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@3.6
      with:
        cli: 1.10.3.1040

    - name: Run tests not Windows
      if: ${{ matrix.os != 'windows-latest' }}
      run: clojure "-M:test:${{ matrix.clojure-version }}" -M:test -e windows
      shell: bash

    - name: Run tests on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: clojure "-M:test:${{ matrix.clojure-version }}" -i windows
      shell: powershell
