name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java-version: ["8", "11", "17"]
        os: [ubuntu, macOS, windows]
        exclude:
          - java-version: "8"
            os: macOS

    runs-on: ${{ matrix.os }}-latest
    name: test-${{ matrix.os }}-temurin@${{ matrix.java-version }}

    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v3"

    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java-version }}

    - name: "Restore Cache"
      uses: "actions/cache@v3"
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: "${{ runner.os }}-deps-${{ hashFiles('deps.edn','bb.edn') }}"

    - name: Setup Babashka
      uses: DeLaGuardo/setup-clojure@11.0
      with:
        bb: 'latest'

    - name: Tools Versions
      run: |
        java -version
        bb --version

    - name: Run bb tests
      run: |
        bb test:bb

    - name: Run JVM tests
      run: |
        bb test:jvm :clj-all

  test-native:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macOS, windows]
        distribution: [graalvm, graalvm-community]

    runs-on: ${{ matrix.os }}-latest
    name: test-${{ matrix.os }}-${{ matrix.distribution}}-native

    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v3"

    - name: Install GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        # match version babashka uses (or will soon use)
        java-version: '21'
        distribution: ${{ matrix.distribution }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: "Restore Cache"
      uses: "actions/cache@v3"
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: "${{ runner.os }}-deps-${{ hashFiles('deps.edn','bb.edn') }}"

    - name: Setup Babashka
      uses: DeLaGuardo/setup-clojure@11.0
      with:
        bb: 'latest'

    - name: Tools Versions
      run: |
        java -version
        bb --version

    - name: Run tests
      run: |
        bb test:native
