name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java-version: ["8", "11", "17"]
        os: [ubuntu, macOS, windows]

    runs-on: ${{ matrix.os }}-latest
    name: test-${{ matrix.os }}-temurin@${{ matrix.java-version }}

    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v3"

    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java-version }}

    - name: "Restore Cache"
      uses: "actions/cache@v3"
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: "${{ runner.os }}-deps-${{ hashFiles('deps.edn','bb.edn') }}"

    # Temporary, switch to installing from setup-clojure action after next bb released
    - name: Setup Babashka Snapshot (macos,linux)
      if: runner.os != 'windows'
      run: |
        bash <(curl https://raw.githubusercontent.com/babashka/babashka/master/install) --version 1.3.180-SNAPSHOT --dir .
        sudo mv ./bb /usr/local/bin/bb

    # Temporary, switch to installing from setup-clojure action after new bb released
    # No handy installer for Windows, so diy
    - name: Setup Babashka Snapshot (windows)
      if: runner.os == 'windows'
      run: |
        C:\msys64\usr\bin\wget.exe -nv -O bbwin.zip https://github.com/babashka/babashka-dev-builds/releases/download/v1.3.180-SNAPSHOT/babashka-1.3.180-SNAPSHOT-windows-amd64.zip
        Expand-Archive bbwin.zip .
        mkdir C:\bbtools
        mv .\bb.exe C:\bbtools
        echo "C:\bbtools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Tools Versions
      run: |
        java -version
        bb --version

    - name: Run bb tests
      run: |
        bb test:bb

    - name: Run JVM tests
      run: |
        bb test:jvm :clj-all

  test-native:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macOS, windows]

    runs-on: ${{ matrix.os }}-latest
    name: test-${{ matrix.os }}-native

    steps:
    - name: "Checkout code"
      uses: "actions/checkout@v3"

    - name: Install GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        # match version babashka uses
        version: '22.3.1'
        java-version: 19
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: "Restore Cache"
      uses: "actions/cache@v3"
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: "${{ runner.os }}-deps-${{ hashFiles('deps.edn','bb.edn') }}"

    - name: Setup Babashka
      uses: DeLaGuardo/setup-clojure@10.1
      with:
        bb: 'latest'

    - name: Tools Versions
      run: |
        java -version
        bb --version

    - name: Run tests
      run: |
        bb test:native
